services:
  - type: web
    name: network-security-ai
    runtime: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: cd backend && gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: network-security-db
          property: connectionString

databases:
  - name: network-security-db
    databaseName: ainsmdb
    user: ainsmuser